@Api_HostAddress = http://localhost:5044

# @name GetAllCustomers
# @summary Retrieves a list of all customers. Some Customers are already pre-seeded in the system.
GET {{Api_HostAddress}}/api/Customers
Accept: */*

###

# @name CreateCustomer
# @summary Creates a new customer.
POST {{Api_HostAddress}}/api/Customers
Content-Type: application/json

{
  "name": "Test Customer",
  "email": "test@example.com",
  "phone": "123-456-7890",
  "permanentAddress": "123 Main St, City, State, ZIP",
  "shippingAddress": "456 Oak Ave, City, State, ZIP"
}
###

# @name GetAllProducts
# @summary Retrieves a list of all products. Some Products are already pre-seeded in the system.
GET {{Api_HostAddress}}/api/Products
Accept: */*

###

# @name GetAllOrders
# @summary Retrieves a list of all orders.

# Optional Query Parameters:

# orderStatus - Filter orders by their status. Possible values:
# PENDING    = 1001
# PROCESSING = 1002
# SHIPPED    = 1003
# DELIVERED  = 1004
# CANCELED   = 1005
@orderStatus = 

# customerId - Filter orders by a specific customer ID.
@customerId = 

GET {{Api_HostAddress}}/api/Orders?orderStatus={{orderStatus}}&customerId={{customerId}}
Accept: */*

###

# @name GetOrderById
# @summary Retrieves a specific order by its ID.

@OrderId = eb31322c-e700-4cf7-82c9-ab6b2fbfc957

GET {{Api_HostAddress}}/api/Orders/{{OrderId}}
Accept: */*

###

# @name CreateOrder
# @summary Creates a new order.
POST {{Api_HostAddress}}/api/Orders
Content-Type: application/json

{
  "customerId": "20000000-0000-0000-0000-000000000000",
  "items": [
    {
      "itemId": "30000000-0000-0000-0000-000000000000",
      "quantity": 10
    },
    {
      "itemId": "40000000-0000-0000-0000-000000000000",
      "quantity": 20
    }
  ]
}

###

# @name CancelOrder
# @summary Cancels an existing order by its ID.
@CancelOrderId = eb31322c-e700-4cf7-82c9-ab6b2fbfc957
PATCH {{Api_HostAddress}}/api/Orders/CancelOrder/{{CancelOrderId}}
Accept: */*

###